### PR TITLE
Tweak BIND config

### PR DESCRIPTION
**Pull request by sevan**
Switch on notifications which means any name servers listed in NS records will be notified.
By turning on notifications, you do not need to explicitly define servers to
notfiy.
Use an ACL to define the Esgob name server IP addresses
Use ACL in allow-transfer statement.
Use tabs to indent the config.

	modified:   templates/secondary_dns.html

### CODE REVIEW

**Comment by kooky** [comment]
I don't think this works when you are setting up secondary DNS to start off.
When starting to use the service, you probably don't want to add an NS pointing at ns1.esgob.com until you are sure it works.  At this stage you can remove the also-notify's to neaten up.  They do no harm.

notify=yes is the default anyway.

I like the use of the ACL though.  Makes config neater.

Just my 2p, and it is Nat's site.

**Comment by natm** [comment]
Will test this!

**Comment by sevan** [comment]
I closed the pull request as I'd made a mistake.
You need the allow-transfer statement because the IP addresses the transfers are made from are not the same as the ones listed in NS records, the notify statement is then moot.
It appears that you can't use a ACL to define servers which should be notified in a allow-transfer statement.
So the only thing left is ACL vs explicit declaration of IP addresses, at which point I thought the original example was less lines though the ACL approach is best practice.

**Comment by natm** [comment]
thanks for clarifying.

**Pull request closed without merging**
